2021 06 21
IMIO/ideabox.policy pull request #1
Opened 2021-06-23 08:22 UTC by boulch

Salut Martin, 

Si tu veux bien, est-ce que tu pourrais faire un peu de code reviewing et me dire si c'est ok pour toi? 

Les modifications sont les suivantes : 
- ajout d'un champs campaign_emails sur les campagnes + cascading si pas de mail spécifié là (va chercher le mail dans la config de ideabox)
- Ajout d'un champs "project_directly_submitted" dans le controlpanel pour choisir de publié directement le projet ou le laisser en brouillon. (upgrade step pour la registry)
- Mie à jour de la config faceted pour ajouter un filtre sur le WF (on ne doit pas récupérer les projets qui restent en brouillon)
  Upgrade step également pour écraser les config des campagnes existantes.

Merci à toi.

2021-06-24 08:39 UTC, mpeeters requested changes

2021-06-24 08:39 UTC, mpeeters commented on src/ideabox/policy/faceted/config/campaign.xml
> +    <element value="private"/>
Private state should not be selected by default

2021-06-24 08:39 UTC, mpeeters commented on src/ideabox/policy/form/project_submission.py
> +            list_mail = email.split(";")
For performance, it is better to first check if there is an email on context (campaign) before getting it from global config (registry). By doing that you can avoid a ZODB query.

2021-06-24 08:39 UTC, mpeeters commented on src/ideabox/policy/form/project_submission.py
> +            default=None,
default should be True

2021-06-24 08:39 UTC, mpeeters commented on src/ideabox/policy/content/campaign.py
> +        description=_(u'You can set many mails address separated with ";"'),
The description should mention the purpose of this field : This email addresses are used to send notification when a new project is proposed by an user.

2021-06-24 08:39 UTC, mpeeters commented on src/ideabox/policy/content/campaign.py
> +        title=_(u"Mails address"),
Should be Email addresses

2021-06-28 13:33 UTC, boulch commented
Done : 
https://github.com/IMIO/ideabox.policy/commits/2021_06_21

2021-06-28 13:59 UTC, mpeeters approved these changes
LGTM

2021-06-28 13:59 UTC, merged